apiVersion: v1
kind: ConfigMap
metadata:
  name: devpulse-config
  namespace: devpulse
data:
  OpenSearch__Endpoint: "https://vpc-devpulse-opensearch-y535mipgihecffjb5l4ehfh6su.us-east-1.es.amazonaws.com"
  OpenSearch__AuthMode: "BasicAuth"
  OpenSearch__CommitsIndex: "devpulse-commits"
  OpenSearch__PullRequestsIndex: "devpulse-pull-requests"
  OpenSearch__ReviewsIndex: "devpulse-reviews"
  RabbitMq__HostName: "devpulse-rabbitmq"