apiVersion: apps/v1
kind: Deployment
metadata:
  name: devpulse-rabbitmq
  namespace: devpulse
  labels:
    app: devpulse-rabbitmq
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: devpulse-rabbitmq
  template:
    metadata:
      labels:
        app: devpulse-rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: 877766546073.dkr.ecr.us-east-1.amazonaws.com/devpulse/rabbitmq:3-management
          ports:
            - name: amqp
              containerPort: 5672
            - name: http
              containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: devpulse-rabbitmq-secret
                  key: RabbitMq__Username
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: devpulse-rabbitmq-secret
                  key: RabbitMq__Password
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: devpulse-rabbitmq
  namespace: devpulse
  labels:
    app: devpulse-rabbitmq
spec:
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
    - name: http
      port: 15672
      targetPort: http
  selector:
    app: devpulse-rabbitmq
