apiVersion: apps/v1
kind: Deployment
metadata:
  name: devpulse-worker
  namespace: devpulse
  labels:
    app: devpulse-worker
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: devpulse-worker
  template:
    metadata:
      labels:
        app: devpulse-worker
    spec:
      containers:
        - name: devpulse-worker
          image: 877766546073.dkr.ecr.us-east-1.amazonaws.com/devpulse/worker:latest
          imagePullPolicy: Always
          env:
            - name: DOTNET_ENVIRONMENT
              value: "Production"
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: devpulse-db-secret
                  key: DatabaseSettings__ConnectionString
            - name: OpenSearch__Endpoint
              valueFrom:
                configMapKeyRef:
                  name: devpulse-config
                  key: OpenSearch__Endpoint
            - name: OpenSearch__AuthMode
              valueFrom:
                configMapKeyRef:
                  name: devpulse-config
                  key: OpenSearch__AuthMode
            - name: OpenSearch__Username
              valueFrom:
                secretKeyRef:
                  name: devpulse-opensearch-secret
                  key: OpenSearch__Username
            - name: OpenSearch__Password
              valueFrom:
                secretKeyRef:
                  name: devpulse-opensearch-secret
                  key: OpenSearch__Password
            - name: RabbitMq__HostName
              valueFrom:
                configMapKeyRef:
                  name: devpulse-config
                  key: RabbitMq__HostName
            - name: RabbitMq__Username
              valueFrom:
                secretKeyRef:
                  name: devpulse-rabbitmq-secret
                  key: RabbitMq__Username
            - name: RabbitMq__Password
              valueFrom:
                secretKeyRef:
                  name: devpulse-rabbitmq-secret
                  key: RabbitMq__Password
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
