// <auto-generated />
using System;
using DevPulse.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DevPulse.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260725154714_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DevPulse.Core.Entities.ArchitecturalPattern", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("id");

                    b.Property<decimal>("CohesionScore")
                        .HasColumnType("numeric")
                        .HasJsonPropertyName("cohesion_score");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasJsonPropertyName("component_name");

                    b.Property<decimal>("CouplingScore")
                        .HasColumnType("numeric")
                        .HasJsonPropertyName("coupling_score");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("detected_at");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("file_path");

                    b.Property<int>("LineCount")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("line_count");

                    b.Property<string>("PatternType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasJsonPropertyName("pattern_type");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("repository_id");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.ToTable("ArchitecturalPatterns");
                });

            modelBuilder.Entity("DevPulse.Core.Entities.CodeHealthScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("id");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("calculated_at");

                    b.Property<int>("CodeSmellCount")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("code_smell_count");

                    b.Property<int>("ComplexityScore")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("complexity_score");

                    b.Property<decimal>("DocumentationScore")
                        .HasColumnType("numeric")
                        .HasJsonPropertyName("documentation_score");

                    b.Property<int>("DuplicationPercentage")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("duplication_percentage");

                    b.Property<decimal>("MaintainabilityScore")
                        .HasColumnType("numeric")
                        .HasJsonPropertyName("maintainability_score");

                    b.Property<decimal>("OverallScore")
                        .HasColumnType("numeric")
                        .HasJsonPropertyName("overall_score");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("repository_id");

                    b.Property<int>("TechnicalDebtMinutes")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("technical_debt_minutes");

                    b.Property<decimal>("TestCoverageScore")
                        .HasColumnType("numeric")
                        .HasJsonPropertyName("test_coverage_score");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "CalculatedAt");

                    b.ToTable("CodeHealthScores");
                });

            modelBuilder.Entity("DevPulse.Core.Entities.Commit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("id");

                    b.Property<int>("Additions")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("additions");

                    b.Property<string>("AuthorEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("author_email");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("author_id");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasJsonPropertyName("author_name");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasJsonPropertyName("branch");

                    b.Property<DateTime>("CommittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("committed_at");

                    b.Property<int>("Deletions")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("deletions");

                    b.Property<int>("FilesChanged")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("files_changed");

                    b.Property<DateTime>("IndexedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("indexed_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("message");

                    b.Property<string>("ParentSha")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasJsonPropertyName("parent_sha");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("repository_id");

                    b.Property<string>("Sha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasJsonPropertyName("sha");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CommittedAt");

                    b.HasIndex("RepositoryId", "Sha")
                        .IsUnique();

                    b.ToTable("Commits");
                });

            modelBuilder.Entity("DevPulse.Core.Entities.CommitFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("id");

                    b.Property<int>("Additions")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("additions");

                    b.Property<int>("ChangeType")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("change_type");

                    b.Property<Guid>("CommitId")
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("commit_id");

                    b.Property<int>("Deletions")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("deletions");

                    b.Property<string>("DiffSnippet")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasJsonPropertyName("diff_snippet");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("file_path");

                    b.HasKey("Id");

                    b.HasIndex("CommitId");

                    b.ToTable("CommitFiles");
                });

            modelBuilder.Entity("DevPulse.Core.Entities.DeveloperMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("id");

                    b.Property<decimal>("AveragePrMergeTime")
                        .HasColumnType("numeric")
                        .HasJsonPropertyName("average_pr_merge_time");

                    b.Property<decimal>("AverageReviewTime")
                        .HasColumnType("numeric")
                        .HasJsonPropertyName("average_review_time");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("calculated_at");

                    b.Property<decimal>("CodeChurnRate")
                        .HasColumnType("numeric")
                        .HasJsonPropertyName("code_churn_rate");

                    b.Property<int>("IssuesClosed")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("issues_closed");

                    b.Property<int>("LinesAdded")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("lines_added");

                    b.Property<int>("LinesDeleted")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("lines_deleted");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("period_end");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("period_start");

                    b.Property<int>("PeriodType")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("period_type");

                    b.Property<int>("PullRequestsReviewed")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("pull_requests_reviewed");

                    b.Property<Guid?>("RepositoryId")
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("repository_id");

                    b.Property<int>("TotalCommits")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("total_commits");

                    b.Property<int>("TotalPullRequests")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("total_pull_requests");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("UserId", "RepositoryId", "PeriodType", "PeriodStart")
                        .IsUnique();

                    b.ToTable("DeveloperMetrics");
                });

            modelBuilder.Entity("DevPulse.Core.Entities.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasJsonPropertyName("file_name");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("file_size_bytes");

                    b.Property<bool>("IsOptimized")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("is_optimized");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasJsonPropertyName("mime_type");

                    b.Property<string>("OptimizedS3Key")
                        .HasColumnType("text")
                        .HasJsonPropertyName("optimized_s3_key");

                    b.Property<Guid?>("PullRequestId")
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("pull_request_id");

                    b.Property<Guid?>("RepositoryId")
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("repository_id");

                    b.Property<string>("S3Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("s3_key");

                    b.Property<string>("S3Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("s3_url");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("type");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("uploaded_at");

                    b.Property<Guid>("UploadedById")
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("uploaded_by_id");

                    b.HasKey("Id");

                    b.HasIndex("PullRequestId");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("UploadedById");

                    b.ToTable("MediaAssets");
                });

            modelBuilder.Entity("DevPulse.Core.Entities.ProjectToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("created_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("is_revoked");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasJsonPropertyName("name");

                    b.Property<int>("Permissions")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("permissions");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("repository_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("ProjectTokens");
                });

            modelBuilder.Entity("DevPulse.Core.Entities.PullRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("id");

                    b.Property<int>("Additions")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("additions");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("author_id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("closed_at");

                    b.Property<int>("CommitCount")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("commit_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("created_at");

                    b.Property<int>("Deletions")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("deletions");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasJsonPropertyName("description");

                    b.Property<int>("FilesChanged")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("files_changed");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("is_draft");

                    b.Property<DateTime?>("MergedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("merged_at");

                    b.Property<Guid?>("MergedById")
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("merged_by_id");

                    b.Property<int>("PrNumber")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("pr_number");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("repository_id");

                    b.Property<string>("SourceBranch")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasJsonPropertyName("source_branch");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("state");

                    b.Property<string>("TargetBranch")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasJsonPropertyName("target_branch");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasJsonPropertyName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("MergedById");

                    b.HasIndex("State");

                    b.HasIndex("RepositoryId", "PrNumber")
                        .IsUnique();

                    b.ToTable("PullRequests");
                });

            modelBuilder.Entity("DevPulse.Core.Entities.PullRequestReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasJsonPropertyName("comment");

                    b.Property<Guid>("PullRequestId")
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("pull_request_id");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("reviewer_id");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("state");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("submitted_at");

                    b.HasKey("Id");

                    b.HasIndex("PullRequestId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("PullRequestReviews");
                });

            modelBuilder.Entity("DevPulse.Core.Entities.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("id");

                    b.Property<string>("CloneUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("clone_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("created_at");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasJsonPropertyName("default_branch");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasJsonPropertyName("description");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("external_id");

                    b.Property<int>("ForkCount")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("fork_count");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasJsonPropertyName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("is_active");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("is_private");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("last_synced_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasJsonPropertyName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("owner_id");

                    b.Property<int>("Provider")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("provider");

                    b.Property<int>("StarCount")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("star_count");

                    b.HasKey("Id");

                    b.HasIndex("FullName")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.HasIndex("Provider", "ExternalId")
                        .IsUnique();

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("DevPulse.Core.Entities.RepositoryContributor", b =>
                {
                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("repository_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("user_id");

                    b.Property<int>("CommitCount")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("commit_count");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("joined_at");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("role");

                    b.HasKey("RepositoryId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("RepositoryContributors");
                });

            modelBuilder.Entity("DevPulse.Core.Entities.ReviewComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("created_at");

                    b.Property<string>("FilePath")
                        .HasColumnType("text")
                        .HasJsonPropertyName("file_path");

                    b.Property<int?>("LineNumber")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("line_number");

                    b.Property<Guid>("PullRequestId")
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("pull_request_id");

                    b.Property<Guid?>("ReviewId")
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("review_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PullRequestId");

                    b.HasIndex("ReviewId");

                    b.ToTable("ReviewComments");
                });

            modelBuilder.Entity("DevPulse.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasJsonPropertyName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasJsonPropertyName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DevPulse.Core.Entities.ArchitecturalPattern", b =>
                {
                    b.HasOne("DevPulse.Core.Entities.Repository", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevPulse.Core.Entities.CodeHealthScore", b =>
                {
                    b.HasOne("DevPulse.Core.Entities.Repository", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevPulse.Core.Entities.Commit", b =>
                {
                    b.HasOne("DevPulse.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DevPulse.Core.Entities.Repository", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevPulse.Core.Entities.CommitFile", b =>
                {
                    b.HasOne("DevPulse.Core.Entities.Commit", null)
                        .WithMany()
                        .HasForeignKey("CommitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevPulse.Core.Entities.DeveloperMetric", b =>
                {
                    b.HasOne("DevPulse.Core.Entities.Repository", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DevPulse.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevPulse.Core.Entities.MediaAsset", b =>
                {
                    b.HasOne("DevPulse.Core.Entities.PullRequest", null)
                        .WithMany()
                        .HasForeignKey("PullRequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DevPulse.Core.Entities.Repository", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DevPulse.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DevPulse.Core.Entities.ProjectToken", b =>
                {
                    b.HasOne("DevPulse.Core.Entities.Repository", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevPulse.Core.Entities.PullRequest", b =>
                {
                    b.HasOne("DevPulse.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevPulse.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("MergedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DevPulse.Core.Entities.Repository", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevPulse.Core.Entities.PullRequestReview", b =>
                {
                    b.HasOne("DevPulse.Core.Entities.PullRequest", null)
                        .WithMany()
                        .HasForeignKey("PullRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevPulse.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DevPulse.Core.Entities.Repository", b =>
                {
                    b.HasOne("DevPulse.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DevPulse.Core.Entities.RepositoryContributor", b =>
                {
                    b.HasOne("DevPulse.Core.Entities.Repository", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevPulse.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DevPulse.Core.Entities.ReviewComment", b =>
                {
                    b.HasOne("DevPulse.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevPulse.Core.Entities.PullRequest", null)
                        .WithMany()
                        .HasForeignKey("PullRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevPulse.Core.Entities.PullRequestReview", null)
                        .WithMany()
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
